name: webroot工作流
on: push
jobs:
  check-environment:
    runs-on: ubuntu-latest
    steps:
      - name: check node version
        run: node -v
      - name: check npm version
        run: npm -v

  build:
    name: 执行build打包构建
    runs-on: ubuntu-latest

    steps: 
      - name: 克隆项目代码到运行环境
        uses: actions/checkout@v4

      - name: 安装依赖
        run: npm install
        
      - name: 构建打包
        run: npm run build

      - name: 部署到Github Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with: 
          branch: gh-pages
          folder: dist